export const APPOINTMENT_STATUSES = Object.freeze({
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  NO_SHOW: 'no_show',
  CANCEL_REQUESTED: 'cancel_requested',
  RESCHEDULE_REQUESTED: 'reschedule_requested',
  RESCHEDULE_REJECTED: 'reschedule_rejected'
});

export const APPOINTMENT_STATUS_VALUES = Object.freeze(Object.values(APPOINTMENT_STATUSES));

export const SLOT_HOLDING_APPOINTMENT_STATUSES = Object.freeze([
  APPOINTMENT_STATUSES.PENDING,
  APPOINTMENT_STATUSES.CONFIRMED,
  APPOINTMENT_STATUSES.IN_PROGRESS,
  APPOINTMENT_STATUSES.CANCEL_REQUESTED,
  APPOINTMENT_STATUSES.RESCHEDULE_REQUESTED,
  APPOINTMENT_STATUSES.COMPLETED
]);

export const QUEUE_ELIGIBLE_APPOINTMENT_STATUSES = Object.freeze([
  APPOINTMENT_STATUSES.CONFIRMED,
  APPOINTMENT_STATUSES.IN_PROGRESS,
  APPOINTMENT_STATUSES.COMPLETED
]);

export const APPOINTMENT_STATUS_TRANSITIONS = Object.freeze({
  [APPOINTMENT_STATUSES.PENDING]: Object.freeze([
    APPOINTMENT_STATUSES.CONFIRMED,
    APPOINTMENT_STATUSES.CANCELLED
  ]),
  [APPOINTMENT_STATUSES.CONFIRMED]: Object.freeze([
    APPOINTMENT_STATUSES.IN_PROGRESS,
    APPOINTMENT_STATUSES.CANCELLED
  ]),
  [APPOINTMENT_STATUSES.IN_PROGRESS]: Object.freeze([
    APPOINTMENT_STATUSES.COMPLETED
  ]),
  [APPOINTMENT_STATUSES.CANCEL_REQUESTED]: Object.freeze([
    APPOINTMENT_STATUSES.CANCELLED,
    APPOINTMENT_STATUSES.CONFIRMED
  ]),
  [APPOINTMENT_STATUSES.RESCHEDULE_REQUESTED]: Object.freeze([
    APPOINTMENT_STATUSES.CONFIRMED,
    APPOINTMENT_STATUSES.RESCHEDULE_REJECTED
  ])
});

export function canTransitionAppointmentStatus(fromStatus, toStatus) {
  return APPOINTMENT_STATUS_TRANSITIONS[fromStatus]?.includes(toStatus) || false;
}

export function appointmentTransitionErrorMessage(fromStatus, toStatus) {
  return `Không thể chuyển lịch từ ${fromStatus} sang ${toStatus}`;
}
